### ISSUE TITLE
Add support for reading AlReaderXE-Ink annotations from connected Android device

### ISSUE THREAD

**Issue by aik099** [davidfor/calibre-annotations#18]
Hi,

When using `AlReaderXE-Ink` app (installed on the Android-based Onyx Boox e-readers) the annotations are stored in 2 files:

* citations - AlReaderXE-Ink/Sync/cites.txt (example: [cites.txt](https://github.com/davidfor/calibre-annotations/files/7776882/cites.txt))
* bookmarks - AlReaderXE-Ink/Sync/bookmarks.txt (example: [bookmarks.txt](https://github.com/davidfor/calibre-annotations/files/7776881/bookmarks.txt))

Even though Android devices connected via USB don't show up as USB drives, but Calibre is still able to see them via OpenMTP protocol.

File formats, that reader app can open: TXT, HTML, RTF, FB2, FB2.zip, DOC, DOCX, PRC, MOBI, CHM, EPUB, CBR, CBZ

The particular device I'm using is called `Onyx Boox Nova 3` and is detected as `Nova3` in Calibre. The same manufacturer is also producing other devices with the same file architecture, like `Nova2`, `Nova`, `Poke3`, `Note3`, but I'm not sure how each of them is named inside the Calibre. See https://downloads.boox.com/ for the full list.

In contrast to Kindle, the `AlReaderXE-Ink` folder is located at the top level of the device storage (not inside the folder, where books are located). The actual books are located at the top level `Books` folder, but Calibre already knows that by itself.

P.S.
Installing AlReader on any Android device (e.g. phone) can be done via Google Play (see https://play.google.com/store/apps/details?id=com.neverland.alreader). Likely when installed this way top-level folder might be named a bit otherwise, than `AlReaderXE-Ink`, but bookmarks/citations would work the same way.

Thank you.

**Comment by davidfor** [comment]
Sorry, but I do not implement the annotation fetch for applications or devices I do not use. There are enough issues when doing it for the devices I know well, that I am not going to do this blind. Not using the app or device leave me with no interest in doing the work. If someone wants to implement it, I am happy to answer any question, check the code and add it to the plugin, but, I am unlikely to implement the fetch for a device or app that I do not have or use.
