### ISSUE TITLE
support  Moon+ Reader

### ISSUE THREAD

**Issue by Geo123abc** [davidfor/calibre-annotations#19]
Hi,
thanks for your excellent work.
Do you have a try about Moon+ Reader ([Moon+ Reader for Android](  https://www.moondownload.com/  )    )?
This app can export the annotations to a .mrexpt file, which is a plain text, and can be import by this app.
Can you add the function that import .mrexpt annotations to calibre？
thank your again.
look forward the new function.

PS:
I'm sorry，I made a mistake that report your post in MobileRead Forums ([[GUI Plugin] Annotations - MobileRead Forums](  https://www.mobileread.com/forums/showthread.php?t=241206  )    ).

**Comment by davidfor** [comment]
Sorry, but I do not implement the annotation fetch for applications or devices I do not use. There are enough issues when doing it for the devices I know well, that I am not going to do this blind. Not using the app or device leave me with no interest in doing the work. If someone wants to implement it, I am happy to answer any question, check the code and add it to the plugin, but, I am unlikely to implement the fetch for a device or app that I do not have or use.

**Comment by stbenjam** [comment]
I started looking at this.  My Python skills are a bit out of date, but I can probably muddle my way through.

@Geo123abc How are you getting this `.mrexpt` file? When I back up from Moon, I get an `.mrpro` file.


.mrpro is just a zip zip file. Inside:

```
$  file $(ls | sort -h) 
_names.list: ASCII text
1.tag:       data
2.tag:       SQLite Write-Ahead Log, version 3007000
3.tag:       SQLite 3.x database, last written using SQLite version 3022000
4.tag:       SQLite 3.x database, user version 7, last written using SQLite version 3022000
5.tag:       empty
6.tag:       XML 1.0 document, ASCII text, with CRLF line terminators
7.tag:       XML 1.0 document, ASCII text, with CRLF line terminators
8.tag:       XML 1.0 document, ASCII text
9.tag:       XML 1.0 document, ASCII text, with CRLF line terminators
10.tag:      XML 1.0 document, Unicode text, UTF-8 text, with CRLF line terminators
11.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
12.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
13.tag:      XML 1.0 document, ASCII text
14.tag:      XML 1.0 document, ASCII text
15.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
16.tag:      XML 1.0 document, ASCII text
17.tag:      XML 1.0 document, ASCII text
18.tag:      XML 1.0 document, ASCII text
19.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
20.tag:      ASCII text
21.tag:      ASCII text
22.tag:      XML 1.0 document, ASCII text
23.tag:      XML 1.0 document, ASCII text
24.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
25.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
26.tag:      XML 1.0 document, ASCII text
27.tag:      XML 1.0 document, ASCII text
28.tag:      XML 1.0 document, ASCII text
29.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
30.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
31.tag:      ASCII text
32.tag:      ASCII text
33.tag:      XML 1.0 document, ASCII text
34.tag:      ASCII text
35.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
36.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
37.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
```
</details>

It looks like `_names.list` is an index that says what each file is.

```
$ nl _names.list
     1	com.flyersoft.moonreaderp/no_backup/androidx.work.workdb-shm
     2	com.flyersoft.moonreaderp/no_backup/androidx.work.workdb-wal
     3	com.flyersoft.moonreaderp/no_backup/androidx.work.workdb
     4	com.flyersoft.moonreaderp/databases/mrbooks.db
     5	com.flyersoft.moonreaderp/databases/mrbooks.db-journal
     6	com.flyersoft.moonreaderp/shared_prefs/theme_Day 3.xml
     7	com.flyersoft.moonreaderp/shared_prefs/theme_pro 4.xml
     8	com.flyersoft.moonreaderp/shared_prefs/theme_Night Theme.xml
     9	com.flyersoft.moonreaderp/shared_prefs/theme_nature.xml
    10	com.flyersoft.moonreaderp/shared_prefs/network2_gutenberg.org.xml
    11	com.flyersoft.moonreaderp/shared_prefs/network2_feedbooks.com.xml
    12	com.flyersoft.moonreaderp/shared_prefs/theme_Night 3.xml
    13	com.flyersoft.moonreaderp/shared_prefs/positions10.xml
    14	com.flyersoft.moonreaderp/shared_prefs/dict_history.xml
    15	com.flyersoft.moonreaderp/shared_prefs/theme_Day 1.xml
    16	com.flyersoft.moonreaderp/shared_prefs/search_history.xml
    17	com.flyersoft.moonreaderp/shared_prefs/widget.xml
    18	com.flyersoft.moonreaderp/shared_prefs/theme_Day Theme.xml
    19	com.flyersoft.moonreaderp/shared_prefs/theme_pro 1.xml
    20	com.flyersoft.moonreaderp/shared_prefs/favfolders6
    21	com.flyersoft.moonreaderp/shared_prefs/select_bar
    22	com.flyersoft.moonreaderp/shared_prefs/admob.xml
    23	com.flyersoft.moonreaderp/shared_prefs/pdf_toc_failed.xml
    24	com.flyersoft.moonreaderp/shared_prefs/theme_Night 1 (True black).xml
    25	com.flyersoft.moonreaderp/shared_prefs/theme_Outdoor (Pure white).xml
    26	com.flyersoft.moonreaderp/shared_prefs/com.google.android.gms.measurement.prefs.xml
    27	com.flyersoft.moonreaderp/shared_prefs/isFootnoteEpub.xml
    28	com.flyersoft.moonreaderp/shared_prefs/theme_circle_only.xml
    29	com.flyersoft.moonreaderp/shared_prefs/theme_pro 2.xml
    30	com.flyersoft.moonreaderp/shared_prefs/theme_pro 3.xml
    31	com.flyersoft.moonreaderp/shared_prefs/shelf_search
    32	com.flyersoft.moonreaderp/shared_prefs/reader_bar_icons
    33	com.flyersoft.moonreaderp/shared_prefs/options1002.xml
    34	com.flyersoft.moonreaderp/shared_prefs/history.txt
    35	com.flyersoft.moonreaderp/shared_prefs/theme_Night 2.xml
    36	com.flyersoft.moonreaderp/shared_prefs/theme_Day 2.xml
    37	com.flyersoft.moonreaderp/shared_prefs/network2_mobileread.com.xml
```

mrbooks.db (4.tag) seems to be what we want.

```
sqlite> .open 4.tag
sqlite> .tables
android_metadata  covers2           statistics      
books             notes             tmpbooks    
```

And here's an example note:

```
sqlite> .mode line
sqlite> SELECT * from notes ORDER BY time DESC LIMIT 1;
            _id = 6
           book = The Dark Forest (The Three-Body Problem Series)
       filename = /sdcard/Calibre Library/Cixin Liu/The Dark Forest (The Three-Body Problem Series) (221)/The Dark Forest (The Three-Body Problem Se - Cixin Liu.epub
  lowerFilename = /sdcard/calibre library/cixin liu/the dark forest (the three-body problem series) (221)/the dark forest (the three-body problem se - cixin liu.epub
    lastChapter = 6
 lastSplitIndex = 1
   lastPosition = 53184
highlightLength = 471
 highlightColor = 1996532479
           time = 1649798150850
       bookmark = 
           note = 
       original = For the majority of people, what they love exists only in the imagination. The object of their love is not the man or woman of reality, but what he or she is like in their imagination. The person in reality is just a template used for the creation of this dream lover. Eventually, they find out the differences between their dream lover and the template. If they can get used to those differences, then they can be together. If not, they split up. It’s as simple as that.
      underline = 0
  strikethrough = 0
            bak = 0
```

**Comment by Geo123abc** [comment]
> I started looking at this. My Python skills are a bit out of date, but I can probably muddle my way through.
> 
> @Geo123abc How are you getting this `.mrexpt` file? When I back up from _Mo_on, I get an `.mrpro` file.
> 
> .mrpro is just a zip file. Inside:
> 
> ```
> $  file $(ls | sort -h) 
> _names.list: ASCII text
> 1.tag:       data
> 2.tag:       SQLite Write-Ahead Log, version 3007000
> 3.tag:       SQLite 3.x database, last written using SQLite version 3022000
> 4.tag:       SQLite 3.x database, user version 7, last written using SQLite version 3022000
> 5.tag:       empty
> 6.tag:       XML 1.0 document, ASCII text, with CRLF line terminators
> 7.tag:       XML 1.0 document, ASCII text, with CRLF line terminators
> 8.tag:       XML 1.0 document, ASCII text
> 9.tag:       XML 1.0 document, ASCII text, with CRLF line terminators
> 10.tag:      XML 1.0 document, Unicode text, UTF-8 text, with CRLF line terminators
> 11.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 12.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 13.tag:      XML 1.0 document, ASCII text
> 14.tag:      XML 1.0 document, ASCII text
> 15.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 16.tag:      XML 1.0 document, ASCII text
> 17.tag:      XML 1.0 document, ASCII text
> 18.tag:      XML 1.0 document, ASCII text
> 19.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 20.tag:      ASCII text
> 21.tag:      ASCII text
> 22.tag:      XML 1.0 document, ASCII text
> 23.tag:      XML 1.0 document, ASCII text
> 24.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 25.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 26.tag:      XML 1.0 document, ASCII text
> 27.tag:      XML 1.0 document, ASCII text
> 28.tag:      XML 1.0 document, ASCII text
> 29.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 30.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 31.tag:      ASCII text
> 32.tag:      ASCII text
> 33.tag:      XML 1.0 document, ASCII text
> 34.tag:      ASCII text
> 35.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 36.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> 37.tag:      XML 1.0 document, ASCII text, with CRLF line terminators
> ```
> 
> It looks like `_names.list` is an index that says what each file is.
> 
> ```
> $ nl _names.list
>      1	com.flyersoft._mo_onreaderp/no_backup/androidx.work.workdb-shm
>      2	com.flyersoft._mo_onreaderp/no_backup/androidx.work.workdb-wal
>      3	com.flyersoft._mo_onreaderp/no_backup/androidx.work.workdb
>      4	com.flyersoft._mo_onreaderp/databases/mrbooks.db
>      5	com.flyersoft._mo_onreaderp/databases/mrbooks.db-journal
>      6	com.flyersoft._mo_onreaderp/shared_prefs/theme_Day 3.xml
>      7	com.flyersoft._mo_onreaderp/shared_prefs/theme_pro 4.xml
>      8	com.flyersoft._mo_onreaderp/shared_prefs/theme_Night Theme.xml
>      9	com.flyersoft._mo_onreaderp/shared_prefs/theme_nature.xml
>     10	com.flyersoft._mo_onreaderp/shared_prefs/network2_gutenberg.org.xml
>     11	com.flyersoft._mo_onreaderp/shared_prefs/network2_feedbooks.com.xml
>     12	com.flyersoft._mo_onreaderp/shared_prefs/theme_Night 3.xml
>     13	com.flyersoft._mo_onreaderp/shared_prefs/positions10.xml
>     14	com.flyersoft._mo_onreaderp/shared_prefs/dict_history.xml
>     15	com.flyersoft._mo_onreaderp/shared_prefs/theme_Day 1.xml
>     16	com.flyersoft._mo_onreaderp/shared_prefs/search_history.xml
>     17	com.flyersoft._mo_onreaderp/shared_prefs/widget.xml
>     18	com.flyersoft._mo_onreaderp/shared_prefs/theme_Day Theme.xml
>     19	com.flyersoft._mo_onreaderp/shared_prefs/theme_pro 1.xml
>     20	com.flyersoft._mo_onreaderp/shared_prefs/favfolders6
>     21	com.flyersoft._mo_onreaderp/shared_prefs/select_bar
>     22	com.flyersoft._mo_onreaderp/shared_prefs/ad_mo_b.xml
>     23	com.flyersoft._mo_onreaderp/shared_prefs/pdf_toc_failed.xml
>     24	com.flyersoft._mo_onreaderp/shared_prefs/theme_Night 1 (True black).xml
>     25	com.flyersoft._mo_onreaderp/shared_prefs/theme_Outdoor (Pure white).xml
>     26	com.flyersoft._mo_onreaderp/shared_prefs/com.google.android.gms.measurement.prefs.xml
>     27	com.flyersoft._mo_onreaderp/shared_prefs/isFootnoteEpub.xml
>     28	com.flyersoft._mo_onreaderp/shared_prefs/theme_circle_only.xml
>     29	com.flyersoft._mo_onreaderp/shared_prefs/theme_pro 2.xml
>     30	com.flyersoft._mo_onreaderp/shared_prefs/theme_pro 3.xml
>     31	com.flyersoft._mo_onreaderp/shared_prefs/shelf_search
>     32	com.flyersoft._mo_onreaderp/shared_prefs/reader_bar_icons
>     33	com.flyersoft._mo_onreaderp/shared_prefs/options1002.xml
>     34	com.flyersoft._mo_onreaderp/shared_prefs/history.txt
>     35	com.flyersoft._mo_onreaderp/shared_prefs/theme_Night 2.xml
>     36	com.flyersoft._mo_onreaderp/shared_prefs/theme_Day 2.xml
>     37	com.flyersoft._mo_onreaderp/shared_prefs/network2__mo_bileread.com.xml
> ```
> 
> mrbooks.db (4.tag) seems to be what we want.
> 
> ```
> sqlite> .open 4.tag
> sqlite> .tables
> android_metadata  covers2           statistics      
> books             notes             tmpbooks    
> ```
> 
> And here's an example note:
> 
> ```
> sqlite> ._mo_de line
> sqlite> SELECT * from notes ORDER BY time DESC LIMIT 1;
>             _id = 6
>            book = The Dark Forest (The Three-Body Problem Series)
>        filename = /sdcard/Calibre Library/Cixin Liu/The Dark Forest (The Three-Body Problem Series) (221)/The Dark Forest (The Three-Body Problem Se - Cixin Liu.epub
>   lowerFilename = /sdcard/calibre library/cixin liu/the dark forest (the three-body problem series) (221)/the dark forest (the three-body problem se - cixin liu.epub
>     lastChapter = 6
>  lastSplitIndex = 1
>    lastPosition = 53184
> highlightLength = 471
>  highlightColor = 1996532479
>            time = 1649798150850
>        bookmark = 
>            note = 
>        original = For the majority of people, what they love exists only in the imagination. The object of their love is not the man or woman of reality, but what he or she is like in their imagination. The person in reality is just a template used for the creation of this dream lover. Eventually, they find out the differences between their dream lover and the template. If they can get used to those differences, then they can be together. If not, they split up. It’s as simple as that.
>       underline = 0
>   strikethrough = 0
>             bak = 0
> ```

Stephen, thank for thank you very much for your helpful work.

I know you got the `.mrpro` file from: All book -> Options ->Backup.

As far as I know the `mrbooks.db` file keeps all the marks data including the notes you take.

After you make notes in one book, you can get the file named `<your book's name>.mrexpt` by the following steps: reading this book -> content -> Bookmarks ->Share (at the downleft corner) ->Export list to file -> choose the path to save  the file.

look forword your great work.

**Comment by Lolo6000** [comment]
how can i make to have my content when i export file in mrexpt from Moon Reader, because i have pb to read my content,
