### ISSUE TITLE
send annotations back to device

### ISSUE THREAD

**Issue by GianniGi** [davidfor/calibre-annotations#8]
Hello, I've got an old kindle (compatible with the copy notes funcion of calibre), and I'd like to copy the notes to the new paperwhite 4, is it possibile to to this using calibre or your addon? Are there other methods? thanks

**Comment by davidfor** [comment]
Sorry, I didn't see this. I do the support for this plugin via the MobileRead thread: https://www.mobileread.com/forums/showthread.php?t=241206.

This plugin is only fetches the annotations from the devices. It does not store enough information to restore them. And for some devices, it is not possible to do this. For a Kindle, the plugin gets the annotations from the "My Clippings.txt" file. This file is really just a log of annotations. And does not contain enough location information to restore the annotations. And then, the Kindles stores annotations in another location that is used when displaying them on the device. I have no way to read this to get annotations. And have never heard of a way to write to that locations

**Comment by GianniGi** [comment]
Ok thanks

Il dom 27 dic 2020, 00:47 David <notifications@github.com> ha scritto:
